"""remove urls

Revision ID: 0b8b3eb9025e
Revises: 5a8468a30c20
Create Date: 2019-01-04 18:20:02.851657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b8b3eb9025e'
down_revision = '5a8468a30c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='currencies')
    op.drop_column('currencies', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('url', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('url', 'currencies', ['url'], unique=True)
    # ### end Alembic commands ###
